// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/GroVlAn/auth-access/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockrepo creates a new instance of mockrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepo {
	mock := &mockrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepo is an autogenerated mock type for the repo type
type mockrepo struct {
	mock.Mock
}

type mockrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepo) EXPECT() *mockrepo_Expecter {
	return &mockrepo_Expecter{mock: &_m.Mock}
}

// CreatePermission provides a mock function for the type mockrepo
func (_mock *mockrepo) CreatePermission(ctx context.Context, roleID string, permission domain.Permission) error {
	ret := _mock.Called(ctx, roleID, permission)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Permission) error); ok {
		r0 = returnFunc(ctx, roleID, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_CreatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermission'
type mockrepo_CreatePermission_Call struct {
	*mock.Call
}

// CreatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permission domain.Permission
func (_e *mockrepo_Expecter) CreatePermission(ctx interface{}, roleID interface{}, permission interface{}) *mockrepo_CreatePermission_Call {
	return &mockrepo_CreatePermission_Call{Call: _e.mock.On("CreatePermission", ctx, roleID, permission)}
}

func (_c *mockrepo_CreatePermission_Call) Run(run func(ctx context.Context, roleID string, permission domain.Permission)) *mockrepo_CreatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Permission
		if args[2] != nil {
			arg2 = args[2].(domain.Permission)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockrepo_CreatePermission_Call) Return(err error) *mockrepo_CreatePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_CreatePermission_Call) RunAndReturn(run func(ctx context.Context, roleID string, permission domain.Permission) error) *mockrepo_CreatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type mockrepo
func (_mock *mockrepo) CreateRole(ctx context.Context, role domain.Role) (string, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Role) (string, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Role) string); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Role) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type mockrepo_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role domain.Role
func (_e *mockrepo_Expecter) CreateRole(ctx interface{}, role interface{}) *mockrepo_CreateRole_Call {
	return &mockrepo_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, role)}
}

func (_c *mockrepo_CreateRole_Call) Run(run func(ctx context.Context, role domain.Role)) *mockrepo_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Role
		if args[1] != nil {
			arg1 = args[1].(domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_CreateRole_Call) Return(s string, err error) *mockrepo_CreateRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockrepo_CreateRole_Call) RunAndReturn(run func(ctx context.Context, role domain.Role) (string, error)) *mockrepo_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultRole provides a mock function for the type mockrepo
func (_mock *mockrepo) DefaultRole(ctx context.Context) (domain.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DefaultRole")
	}

	var r0 domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_DefaultRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultRole'
type mockrepo_DefaultRole_Call struct {
	*mock.Call
}

// DefaultRole is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockrepo_Expecter) DefaultRole(ctx interface{}) *mockrepo_DefaultRole_Call {
	return &mockrepo_DefaultRole_Call{Call: _e.mock.On("DefaultRole", ctx)}
}

func (_c *mockrepo_DefaultRole_Call) Run(run func(ctx context.Context)) *mockrepo_DefaultRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepo_DefaultRole_Call) Return(role domain.Role, err error) *mockrepo_DefaultRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *mockrepo_DefaultRole_Call) RunAndReturn(run func(ctx context.Context) (domain.Role, error)) *mockrepo_DefaultRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserRole provides a mock function for the type mockrepo
func (_mock *mockrepo) DeleteUserRole(ctx context.Context, userID string, roleID string) error {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_DeleteUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserRole'
type mockrepo_DeleteUserRole_Call struct {
	*mock.Call
}

// DeleteUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
func (_e *mockrepo_Expecter) DeleteUserRole(ctx interface{}, userID interface{}, roleID interface{}) *mockrepo_DeleteUserRole_Call {
	return &mockrepo_DeleteUserRole_Call{Call: _e.mock.On("DeleteUserRole", ctx, userID, roleID)}
}

func (_c *mockrepo_DeleteUserRole_Call) Run(run func(ctx context.Context, userID string, roleID string)) *mockrepo_DeleteUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockrepo_DeleteUserRole_Call) Return(err error) *mockrepo_DeleteUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_DeleteUserRole_Call) RunAndReturn(run func(ctx context.Context, userID string, roleID string) error) *mockrepo_DeleteUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// FullPermissions provides a mock function for the type mockrepo
func (_mock *mockrepo) FullPermissions(ctx context.Context, userID string) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FullPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_FullPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullPermissions'
type mockrepo_FullPermissions_Call struct {
	*mock.Call
}

// FullPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) FullPermissions(ctx interface{}, userID interface{}) *mockrepo_FullPermissions_Call {
	return &mockrepo_FullPermissions_Call{Call: _e.mock.On("FullPermissions", ctx, userID)}
}

func (_c *mockrepo_FullPermissions_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_FullPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_FullPermissions_Call) Return(strings []string, err error) *mockrepo_FullPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockrepo_FullPermissions_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]string, error)) *mockrepo_FullPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// PermissionsByRole provides a mock function for the type mockrepo
func (_mock *mockrepo) PermissionsByRole(ctx context.Context, roleName string) ([]domain.Permission, error) {
	ret := _mock.Called(ctx, roleName)

	if len(ret) == 0 {
		panic("no return value specified for PermissionsByRole")
	}

	var r0 []domain.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Permission, error)); ok {
		return returnFunc(ctx, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Permission); ok {
		r0 = returnFunc(ctx, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roleName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_PermissionsByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermissionsByRole'
type mockrepo_PermissionsByRole_Call struct {
	*mock.Call
}

// PermissionsByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
func (_e *mockrepo_Expecter) PermissionsByRole(ctx interface{}, roleName interface{}) *mockrepo_PermissionsByRole_Call {
	return &mockrepo_PermissionsByRole_Call{Call: _e.mock.On("PermissionsByRole", ctx, roleName)}
}

func (_c *mockrepo_PermissionsByRole_Call) Run(run func(ctx context.Context, roleName string)) *mockrepo_PermissionsByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_PermissionsByRole_Call) Return(permissions []domain.Permission, err error) *mockrepo_PermissionsByRole_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *mockrepo_PermissionsByRole_Call) RunAndReturn(run func(ctx context.Context, roleName string) ([]domain.Permission, error)) *mockrepo_PermissionsByRole_Call {
	_c.Call.Return(run)
	return _c
}

// PermissionsByUser provides a mock function for the type mockrepo
func (_mock *mockrepo) PermissionsByUser(ctx context.Context, userID string) ([]domain.Permission, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PermissionsByUser")
	}

	var r0 []domain.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Permission, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Permission); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_PermissionsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermissionsByUser'
type mockrepo_PermissionsByUser_Call struct {
	*mock.Call
}

// PermissionsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) PermissionsByUser(ctx interface{}, userID interface{}) *mockrepo_PermissionsByUser_Call {
	return &mockrepo_PermissionsByUser_Call{Call: _e.mock.On("PermissionsByUser", ctx, userID)}
}

func (_c *mockrepo_PermissionsByUser_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_PermissionsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_PermissionsByUser_Call) Return(permissions []domain.Permission, err error) *mockrepo_PermissionsByUser_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *mockrepo_PermissionsByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Permission, error)) *mockrepo_PermissionsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceUserRole provides a mock function for the type mockrepo
func (_mock *mockrepo) ReplaceUserRole(ctx context.Context, userID string, oldRoleID string, newRoleID string) error {
	ret := _mock.Called(ctx, userID, oldRoleID, newRoleID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, oldRoleID, newRoleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_ReplaceUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceUserRole'
type mockrepo_ReplaceUserRole_Call struct {
	*mock.Call
}

// ReplaceUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - oldRoleID string
//   - newRoleID string
func (_e *mockrepo_Expecter) ReplaceUserRole(ctx interface{}, userID interface{}, oldRoleID interface{}, newRoleID interface{}) *mockrepo_ReplaceUserRole_Call {
	return &mockrepo_ReplaceUserRole_Call{Call: _e.mock.On("ReplaceUserRole", ctx, userID, oldRoleID, newRoleID)}
}

func (_c *mockrepo_ReplaceUserRole_Call) Run(run func(ctx context.Context, userID string, oldRoleID string, newRoleID string)) *mockrepo_ReplaceUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockrepo_ReplaceUserRole_Call) Return(err error) *mockrepo_ReplaceUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_ReplaceUserRole_Call) RunAndReturn(run func(ctx context.Context, userID string, oldRoleID string, newRoleID string) error) *mockrepo_ReplaceUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// RoleIDByName provides a mock function for the type mockrepo
func (_mock *mockrepo) RoleIDByName(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RoleIDByName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_RoleIDByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleIDByName'
type mockrepo_RoleIDByName_Call struct {
	*mock.Call
}

// RoleIDByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *mockrepo_Expecter) RoleIDByName(ctx interface{}, name interface{}) *mockrepo_RoleIDByName_Call {
	return &mockrepo_RoleIDByName_Call{Call: _e.mock.On("RoleIDByName", ctx, name)}
}

func (_c *mockrepo_RoleIDByName_Call) Run(run func(ctx context.Context, name string)) *mockrepo_RoleIDByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_RoleIDByName_Call) Return(s string, err error) *mockrepo_RoleIDByName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockrepo_RoleIDByName_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *mockrepo_RoleIDByName_Call {
	_c.Call.Return(run)
	return _c
}

// Roles provides a mock function for the type mockrepo
func (_mock *mockrepo) Roles(ctx context.Context, userID string) ([]domain.Role, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Roles")
	}

	var r0 []domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_Roles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roles'
type mockrepo_Roles_Call struct {
	*mock.Call
}

// Roles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) Roles(ctx interface{}, userID interface{}) *mockrepo_Roles_Call {
	return &mockrepo_Roles_Call{Call: _e.mock.On("Roles", ctx, userID)}
}

func (_c *mockrepo_Roles_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_Roles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_Roles_Call) Return(roles []domain.Role, err error) *mockrepo_Roles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *mockrepo_Roles_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Role, error)) *mockrepo_Roles_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRole provides a mock function for the type mockrepo
func (_mock *mockrepo) SetUserRole(ctx context.Context, roleID string, userID string) error {
	ret := _mock.Called(ctx, roleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, roleID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_SetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRole'
type mockrepo_SetUserRole_Call struct {
	*mock.Call
}

// SetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - userID string
func (_e *mockrepo_Expecter) SetUserRole(ctx interface{}, roleID interface{}, userID interface{}) *mockrepo_SetUserRole_Call {
	return &mockrepo_SetUserRole_Call{Call: _e.mock.On("SetUserRole", ctx, roleID, userID)}
}

func (_c *mockrepo_SetUserRole_Call) Run(run func(ctx context.Context, roleID string, userID string)) *mockrepo_SetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockrepo_SetUserRole_Call) Return(err error) *mockrepo_SetUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_SetUserRole_Call) RunAndReturn(run func(ctx context.Context, roleID string, userID string) error) *mockrepo_SetUserRole_Call {
	_c.Call.Return(run)
	return _c
}
