// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package preloader

import (
	"context"

	"github.com/GroVlAn/auth-access/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockrepo creates a new instance of mockrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepo {
	mock := &mockrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepo is an autogenerated mock type for the repo type
type mockrepo struct {
	mock.Mock
}

type mockrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepo) EXPECT() *mockrepo_Expecter {
	return &mockrepo_Expecter{mock: &_m.Mock}
}

// CreatePermission provides a mock function for the type mockrepo
func (_mock *mockrepo) CreatePermission(ctx context.Context, roleID string, permission domain.Permission) error {
	ret := _mock.Called(ctx, roleID, permission)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Permission) error); ok {
		r0 = returnFunc(ctx, roleID, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_CreatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermission'
type mockrepo_CreatePermission_Call struct {
	*mock.Call
}

// CreatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permission domain.Permission
func (_e *mockrepo_Expecter) CreatePermission(ctx interface{}, roleID interface{}, permission interface{}) *mockrepo_CreatePermission_Call {
	return &mockrepo_CreatePermission_Call{Call: _e.mock.On("CreatePermission", ctx, roleID, permission)}
}

func (_c *mockrepo_CreatePermission_Call) Run(run func(ctx context.Context, roleID string, permission domain.Permission)) *mockrepo_CreatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Permission
		if args[2] != nil {
			arg2 = args[2].(domain.Permission)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockrepo_CreatePermission_Call) Return(err error) *mockrepo_CreatePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_CreatePermission_Call) RunAndReturn(run func(ctx context.Context, roleID string, permission domain.Permission) error) *mockrepo_CreatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type mockrepo
func (_mock *mockrepo) CreateRole(ctx context.Context, role domain.Role) (string, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Role) (string, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Role) string); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Role) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type mockrepo_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role domain.Role
func (_e *mockrepo_Expecter) CreateRole(ctx interface{}, role interface{}) *mockrepo_CreateRole_Call {
	return &mockrepo_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, role)}
}

func (_c *mockrepo_CreateRole_Call) Run(run func(ctx context.Context, role domain.Role)) *mockrepo_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Role
		if args[1] != nil {
			arg1 = args[1].(domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_CreateRole_Call) Return(s string, err error) *mockrepo_CreateRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockrepo_CreateRole_Call) RunAndReturn(run func(ctx context.Context, role domain.Role) (string, error)) *mockrepo_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}
